name: Check Tools
on:
  workflow_dispatch:
  
jobs:
  windows:
    runs-on: windows-11-arm
    steps:
      - name: System Architecture
        shell: bash
        run: |
           echo "Python platform.machine(): $(python -c 'import platform; print(platform.machine())')"
           echo "Python platform.architecture(): $(python -c 'import platform; print(platform.architecture())')"
           echo "Python platform.processor(): $(python -c 'import platform; print(platform.processor())')"
           echo "PowerShell \$env:PROCESSOR_ARCHITECTURE: $PROCESSOR_ARCHITECTURE"
           echo "PowerShell \$env:PROCESSOR_IDENTIFIER: $PROCESSOR_IDENTIFIER"
           echo "Openssl version: $(openssl version)"
           echo "Python version: $(python --version)"
           echo "Python3 version: $(python3 --version)"
      - name: Check Windows DisplayVersion (e.g., 25H2)
        shell: pwsh
        run: |
            $cv = Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion"
            [pscustomobject]@{
            ProductName    = $cv.ProductName
            EditionID      = $cv.EditionID
            DisplayVersion = $cv.DisplayVersion
            ReleaseId      = $cv.ReleaseId
            CurrentBuild   = $cv.CurrentBuild
            UBR            = $cv.UBR
            Architecture   = (Get-CimInstance Win32_OperatingSystem).OSArchitecture
            } | Format-List
      - name: Check installed .NET SDKs and runtimes
        shell: pwsh
        run: |
            dotnet --info
            dotnet --list-sdks | findstr "^10\."
            dotnet --list-runtimes
            
      - name: Check Python versions on PATH
        shell: pwsh
        run: |
          where python
          where python3
          python --version
          python3 --version



