name: Check Tools
on:
  workflow_dispatch:
  
jobs:
  windows:
    runs-on: windows-11-arm
    steps:
      - name: System Architecture
        shell: bash
        run: |
           echo "Python platform.machine(): $(python -c 'import platform; print(platform.machine())')"
           echo "Python platform.architecture(): $(python -c 'import platform; print(platform.architecture())')"
           echo "Python platform.processor(): $(python -c 'import platform; print(platform.processor())')"
           echo "PowerShell \$env:PROCESSOR_ARCHITECTURE: $PROCESSOR_ARCHITECTURE"
           echo "PowerShell \$env:PROCESSOR_IDENTIFIER: $PROCESSOR_IDENTIFIER"
           echo "Openssl version: $(openssl version)"
           echo "Python version: $(python --version)"
           echo "Python3 version: $(python3 --version)"
      - name: Check Windows SKU and version
        shell: pwsh
        run: |
          Get-ComputerInfo | Select-Object `
          WindowsProductName, `
          WindowsEditionId, `
          WindowsVersion, `
          OsBuildNumber, `
          OsArchitecture

